name: contacts_app
description: "Contacts app based on the design of the iOS native Contacts app."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_swipe_action_cell: ^3.1.4
  go_router: ^14.2.7
  intl: any
  logger: ^2.4.0
  meta: ^1.15.0
  objectbox: ^4.0.2
  objectbox_flutter_libs: any
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: any
  go_router_builder: any
  objectbox_generator: any

flutter:
  generate: true
  assets:
    - assets/initial_contacts.json

objectbox:
  output_dir: core/data/objectbox/generated
